[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "AOC"
path = "src/main.rs"

[[bin]]
name = "AOCTests"
path = "src/tests/main.rs"

[dependencies]
libc = "0.2.171"

[build-dependencies]
libc = "0.2.171"